{{- if and .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
{{- end }}
